version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres_password
  web-app:
    build:
      args: 
        HTTP_PROXY: http://hrdproxy.hrd-s.com:81
        HTTPS_PROXY: http://hrdproxy.hrd-s.com:81
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - '4001:3000'
    restart: on-failure
  to-do-api:
    build:
      args: 
          HTTP_PROXY: http://hrdproxy.hrd-s.com:81
          HTTPS_PROXY: http://hrdproxy.hrd-s.com:81
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - '5001:3001'
    restart: on-failure
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
