version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  web-app:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - '4001:3000'
    restart: on-failure
  to-do-api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - '5001:3001'
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - CHOKIDAR_USEPOLLING="true"
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
